### ISSUE TITLE
mcpi requesterror.

### ISSUE THREAD

**Issue by JamesTheFurryCoder** [arpruss/raspberryjammod#64]
I am trying to use the spawn entity function and it's not working. here is the code.

```
from mine import *

mc = Minecraft()

mc.spawnEntity(10,10,10,VILLAGER)

```

Here's the error I am getting

```
Traceback (most recent call last):
  File "C:\Users\Name\AppData\Roaming\.minecraft\mcpipy\camera.py", line 13, in <module>
    mc.spawnEntity(10,10,10,VILLAGER)
  File "C:\Users\Name\AppData\Roaming\.minecraft\mcpipy\mcpi\minecraft.py", line 264, in spawnEntity
    return int(self.conn.sendReceive("world.spawnEntity", args))
  File "C:\Users\Name\AppData\Roaming\.minecraft\mcpipy\mcpi\connection.py", line 134, in sendReceive
    return self.receive()
  File "C:\Users\Name\AppData\Roaming\.minecraft\mcpipy\mcpi\connection.py", line 128, in receive
    raise RequestError("%s failed"%self.lastSent.strip())
mcpi.connection.RequestError: world.spawnEntity(10,10,10,Villager) failed

```

Is there anything I can do to resolve this error?

**Comment by arpruss** [comment]
The entity goes before the coordinates.

**Comment by JamesParkerStrand** [comment]
> The entity goes before the coordinates.

I tried it out, and went to the coordinates, but nothing seems to spawn anything. I would get a message in chat saying exeception catched, absent = 0. So i Tried MCPI module too. that didnt work etiher

```
from mcpi.minecraft import *
from mcpi.entity import *

mc = Minecraft.create()

pos = mc.player.getPos()
mc.postToChat("hello")

mc.spawnEntity(ZOMBIE,10, 65, 10)
```
for this code, I don't get that exception catched error posted in chat. but still nothing happens

**Comment by JamesTheFurryCoder** [comment]
> The entity goes before the coordinates.

Thanks, it worked
